name: Validate PR on main branch

# The workflow will run whenever an event happens on a pull request
on:
  push:
    branches: [ "main" ]
  pull_request:
      types: [opened, synchronize]
      branches: [ master]
      paths:
        - 'force-app/**'
jobs:
   validate-deployment-on-develop-org:
     runs-on: ubuntu-latest
        if:${{ github.actor != 'dependabot[bot]' }}
     steps:
            
            - uses: actions/setup-node@v2
              with:
                node-version: '14'
            - name: 'Checkout source code'
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
